# Generated by Django 4.2.27 on 2026-05-18 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fishing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('bite_status', models.CharField(choices=[('active', ' Кълве'), ('weak', ' Слаба активност'), ('capo', '❌ Капо')], default='weak', max_length=10, verbose_name='Активност на рибата')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Picture of fishing spot')),
                ('content', models.TextField(verbose_name='Tell me about the adventure')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(choices=[('0', 'Draft'), ('1', 'Publish')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='fishing_app.fishingplace', verbose_name='Location')),
            ],
        ),
    ]
