# Generated by Django 4.2.27 on 2026-02-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_app', '0003_alter_fishingplace_map_embed_and_more'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='fishing_app.fishingplace', verbose_name='Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.TextField(choices=[('0', 'Draft'), ('1', 'Publish')], default=0),
        ),
    ]
