# Generated by Django 4.2.27 on 2026-05-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bite_status',
            field=models.CharField(choices=[('active', 'Кълве много'), ('weak', 'Слаба активност / Рядко пипаше '), ('capo', '❌ Капочино')], default='weak', max_length=10, verbose_name='Активност на рибата'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Publish')], default='1', max_length=1),
        ),
    ]
