# Generated by Django 4.2.27 on 2026-02-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_location_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.TextField(choices=[('0', 'Draft'), ('1', 'Publish')], default=1),
        ),
    ]
