# Generated by Django 4.2.27 on 2026-05-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Fish kind')),
            ],
            options={
                'verbose_name_plural': 'Fishes',
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Method')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description of the tactic')),
                ('image', models.ImageField(blank=True, null=True, upload_to='methods/')),
            ],
        ),
        migrations.CreateModel(
            name='FishingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Object')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('place_type', models.CharField(choices=[('river', 'river'), ('lake', 'lake'), ('swamp', 'swamp')], max_length=10, verbose_name='Type of reservoir')),
                ('region', models.CharField(default='Pleven', max_length=10, verbose_name='Region')),
                ('description', models.TextField(verbose_name='Info for location')),
                ('image', models.ImageField(upload_to='places/', verbose_name='Picture')),
                ('map_embed', models.TextField(blank=True, null=True, verbose_name='Google Maps Embed Code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude', max_digits=9, null=True)),
                ('access_type', models.CharField(choices=[('free', 'Свободен достъп (с билет)'), ('paid', 'Платен обект (такса)')], default='free', max_length=10, verbose_name='Access type')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Recommended Spot (Top 5)')),
                ('fishes', models.ManyToManyField(related_name='places', to='fishing_app.fish', verbose_name='Types of fish here')),
                ('methods', models.ManyToManyField(related_name='places', to='fishing_app.method', verbose_name='Appropriate methods')),
            ],
        ),
    ]
